'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Year_11_Dynamic_Grade_data.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property class_percentage_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("class percentage button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property common_button_blue_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common-button-blue-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property department_percentage_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("department percentage button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ecclesbourne_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ecclesbourne logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property predict_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("predict button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property student_classes_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("student classes button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property student_details_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("student details button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Subject_percentage_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Subject percentage button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teacher_class_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teacher class button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teacher_details_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teacher details button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Throbber_allbackgrounds_circledots_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Throbber_allbackgrounds_circledots_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property throbber_load_gif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("throbber load gif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titlebg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titlebg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titlebg_editadd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titlebg editadd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titlebg_editadd_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titlebg editadd 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Titlebg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titlebg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_grades_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view grades button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_percentage_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view percentage button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
